apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: mt4zdr7pk-go 
  description: Secure Supply Chain Example for Go Runtime http based application with advanced continuous integration pipeline covering building, CVE scanning, security scanning, signatures,  attestations, SLSA provenance and SBOM along with Gitops-based continuous deployment   
  links:
    - url: https://www.redhat.com/en/solutions/trusted-software-supply-chain
      title: Trusted Secure Supply Chain 
      icon: dashboard
      type: admin-dashboard
  annotations:
    # ArgoCD apps from this template used tssc-gitops as the grouping
    argocd/app-selector: tssc/gitops=mt4zdr7pk-go
    backstage.io/kubernetes-id: mt4zdr7pk-go 
    backstage.io/techdocs-ref: dir:. 
    jenkins.io/job-full-name: mt4zdr7pk-go
    jfrog-artifactory/image-name: rhtap-qe-go
  tags: ["go", "sscs", "sbom", "acs"] 
spec:
  type: service
  owner: user:guest 
  lifecycle: experimental
 